name: build-test-publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  lint-test-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] #macos-latest, windows-latest,
        node: ['14.x', '16.x']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
          
      - name: npm install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: 'npm run test:cov'
      - name: build
        run: 'npm run build'
      - name: cache
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == '16.x'}}
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./dist/*
          key: ${{ github.sha }}


  publish:
    needs: lint-test-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./dist/*
          key: ${{ github.sha }}
      - name: install zx
        run: 'npm i -g zx'
      - name: publish-dry-run
        run: npm publish --dry-run
      - name: publish package
        run: zx ./publish.mjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
