name: build-test-publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: npm install
        run: npm ci
      - name: build
        run: npm build
      - name: test
        run: 'npm test:cov'
      - name: delete node modules
        run: rm -rf ./node_modules
      - name: npm install - prod
        run: 'npm ci --production'
      - name: build - prod
        run: 'npm build:prod'
      - name: install zx
        run: 'npm i -g zx'
      - name: publish package
        run: zx ./publish.mjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

